app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls','bases'), namespace='bases')),
    path('inv/', include(('inv.urls','inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls','cmp'), namespace='cmp')),
    path('admin/', admin.site.urls),
]

app/inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, SubCategoriaView, \
        SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
        MarcaView, MarcaNew, MarcaEdit, MarcaInactivar, \
        UnidadMedidaView, UnidadMedidaNew, UnidadMedidaEdit, UnidadMedidaInactivar, \
        ProductoView, ProductoNew, ProductoEdit, ProductoInactivar

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name="categoria_list"),
    path('categoria/new', CategoriaNew.as_view(), name="categoria_new"),
    path('categoria/edit/<int:pk>', CategoriaEdit.as_view(), name="categoria_edit"),
    path('categoria/delete/<int:pk>', CategoriaDel.as_view(), name="categoria_del"),
    
    path('subcategorias/', SubCategoriaView.as_view(), name="subcategoria_list"),
    path('subcategoria/new', SubCategoriaNew.as_view(), name="subcategoria_new"),
    path('subcategoria/edit/<int:pk>', SubCategoriaEdit.as_view(), name="subcategoria_edit"),
    path('subcategoria/delete/<int:pk>', SubCategoriaDel.as_view(), name="subcategoria_del"),    

    path('marcas/', MarcaView.as_view(), name="marca_list"),
    path('marcas/new', MarcaNew.as_view(), name="marca_new"),
    path('marcas/edit/<int:pk>', MarcaEdit.as_view(), name="marca_edit"),
    path('marcas/inactivar/<int:id>', MarcaInactivar, name="marca_inactivar"),

    path('unidadesmedida/', UnidadMedidaView.as_view(), name="unidad_medida_list"),
    path('unidadesmedidas/new', UnidadMedidaNew.as_view(), name="unidad_medida_new"),
    path('unidadesmedidas/edit/<int:pk>', UnidadMedidaEdit.as_view(), name="unidad_medida_edit"),
    path('unidadesmedidas/inactivar/<int:id>', UnidadMedidaInactivar, name="unidad_medida_inactivar"),

    path('producto/', ProductoView.as_view(), name="producto_list"),
    path('producto/new', ProductoNew.as_view(), name="producto_new"),
    path('producto/edit/<int:pk>', ProductoEdit.as_view(), name="producto_edit"),
    path('producto/inactivar/<int:id>', ProductoInactivar, name="producto_inactivar"),

]

app/bases/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ClaseModelo(models.Model):
    estado = models.BooleanField("Estado", default=True)
    fecha_Creacion = models.DateTimeField("Fecha Creacion", auto_now_add= True)
    fecha_Modificado = models.DateTimeField("Fecha Modificacion", auto_now=True)
    usuario_Crea = models.ForeignKey(User, on_delete=models.CASCADE)
    usuario_Modifica = models.IntegerField("Usuario Modifica", null=True, blank=True)

    class Meta:
        abstract=True 

app/inv/models.py
from django.db import models

from bases.models import ClaseModelo

# Create your models here.

class Categoria(ClaseModelo):
    descripcion = models.CharField("Descripcion", max_length=100, help_text="Descripcion de la categoria", unique=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria,self).save()

    class Meta:
        verbose_name_plural = "Categorias"


class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField("Descripcion", max_length=100, help_text="Descripcion de la sub categoria", unique=True)

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)


    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria,self).save()

    class Meta:
        verbose_name_plural = "Sub Categorias"
        unique_together = ('categoria', 'descripcion')


class Marca(ClaseModelo):
    descripcion = models.CharField("Descripcion", max_length=100, help_text="Descripcion de la marca", unique=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca,self).save()

    class Meta:
        verbose_name_plural = "Marcas"        


class UnidadMedida(ClaseModelo):
    descripcion = models.CharField("Descripcion", max_length=100, help_text="Descripcion de la Unidad de Medida", unique=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadMedida,self).save()

    class Meta:
        verbose_name_plural = "Unidades de Medida"        


class Producto(ClaseModelo):
    codigo = models.CharField("Codigo", max_length=20, null=False, unique=True)
    codigo_barra = models.CharField("Codigo Barra", max_length=50, null=False, unique=True)
    descripcion = models.CharField("Descripcion", max_length=200, help_text="Descripcion del Producto", unique=True, null=False)
    precio = models.FloatField("Precio", max_length=15, default=0)
    existencia = models.IntegerField("Existencia", default=0)
    ultima_compra = models.DateTimeField("Ultima Compra", null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    unidadmedida = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE)

    

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto,self).save()

    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('codigo', 'codigo_barra')        

app/inv/forms.py
from django import forms
from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion':'Descripcion de la Categoria',
                'estado':'Estado'}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })


class SubCategoriaForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset = Categoria.objects.filter(estado=True)
        .order_by('descripcion')
    )
    class Meta:
        model = SubCategoria
        fields = ['categoria', 'descripcion', 'estado']
        labels = {'descripcion':'Sub Categoria',
                'estado':'Estado'}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['categoria'].empty_label = "Seleccione Categoria"


class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ['descripcion', 'estado']
        labels = {'descripcion':'Descripcion de la Marca',
                'estado':'Estado'}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })


class UnidadMedidaForm(forms.ModelForm):
    class Meta:
        model = UnidadMedida
        fields = ['descripcion', 'estado']
        labels = {'descripcion':'Descripcion de la unidad de medida',
                'estado':'Estado'}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo', 'codigo_barra','descripcion', 'estado', \
            'precio', 'existencia', 'ultima_compra',
            'marca', 'subcategoria', 'unidadmedida']

        exclude = ['fecha_Creacion', 'fecha_Modificado', 'usuario_Crea', 'usuario_Modifica']
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True

app/inv/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib.auth.decorators import login_required, permission_required

from .models import Categoria, SubCategoria, Marca, UnidadMedida, Producto
from .forms import CategoriaForm, SubCategoriaForm, MarcaForm, UnidadMedidaForm, ProductoForm

from bases.views import SinPrivilegios
class CategoriaView(SinPrivilegios, generic.ListView):
    permission_required = "inv.view_categoria"
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    

class CategoriaNew(SuccessMessageMixin, SinPrivilegios, generic.CreateView):
    permission_required = "inv.add_categoria"
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inv:categoria_list")
    success_message = "Categoria Creada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.usuario_Crea = self.request.user
        return super().form_valid(form)


class CategoriaEdit(SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "inv.change_categoria"
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inv:categoria_list")
    
    success_message = "Categoria Actualizada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.usuario_Modifica = self.request.user.id
        return super().form_valid(form)


class CategoriaDel(SinPrivilegios, generic.DeleteView):
    permission_required = "inv.delete_categoria"
    model = Categoria
    template_name = "inv/categoria_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy("inv:categoria_list")


class SubCategoriaView(SinPrivilegios, generic.ListView):
    permission_required = "inv.view_subcategoria"
    model = SubCategoria
    template_name = "inv/subcategoria_list.html"
    context_object_name = "obj"


class SubCategoriaNew(SinPrivilegios, generic.CreateView):
    permission_required = "inv.add_subcategoria"
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    
    
    def form_valid(self, form):
        form.instance.usuario_Crea = self.request.user
        return super().form_valid(form)


class SubCategoriaEdit(SinPrivilegios, generic.UpdateView):
    permission_required = "inv.change_subcategoria"
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    
    
    def form_valid(self, form):
        form.instance.usuario_Modifica = self.request.user.id
        return super().form_valid(form)


class SubCategoriaDel(SinPrivilegios, generic.DeleteView):
    permission_required = "inv.delete_subcategoria"
    model = SubCategoria
    template_name = "inv/marca_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy("inv:subcategoria_list")


class MarcaView(SinPrivilegios, generic.ListView):
    permission_required = "inv.view_marca"
    model = Marca
    template_name = "inv/marca_list.html"
    context_object_name = "obj"

    
class MarcaNew(SinPrivilegios, generic.CreateView):
    permission_required = "inv.add_marca"
    model = Marca
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForm
    success_url = reverse_lazy("inv:marca_list")
    
    def form_valid(self, form):
        form.instance.usuario_Crea = self.request.user
        return super().form_valid(form)


class MarcaEdit(SinPrivilegios, generic.UpdateView):
    permission_required = "inv.change_marca"
    model = Marca
    template_name = "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForm
    success_url = reverse_lazy("inv:marca_list")
    
    def form_valid(self, form):
        form.instance.usuario_Modifica = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_marca', login_url='base:sin_privilegios')
def MarcaInactivar(request, id):
    marca = Marca.objects.filter(pk= id).first()
    contexto = {}
    template_name = "inv/marca_del.html"

    if not marca:
        return redirect("inv:marca_list")
    
    if request.method=='GET':
        contexto ={'obj': marca}

    if request.method=='POST':
        marca.estado = False
        marca.save()
        messages.success(request,'Marca Inactivada!.')
        return redirect("inv:marca_list")

    return render(request, template_name, contexto)

#UNIDAD DE MEDIDA
class UnidadMedidaView(SinPrivilegios, generic.ListView):
    permission_required = "inv.view_unidadmedida"
    model = UnidadMedida
    template_name = "inv/unidad_medida_list.html"
    context_object_name = "obj"
    
class UnidadMedidaNew(SinPrivilegios, generic.CreateView):
    permission_required = "inv.add_unidadmedida"
    model = UnidadMedida
    template_name = "inv/unidad_medida_form.html"
    context_object_name = "obj"
    form_class = UnidadMedidaForm
    success_url = reverse_lazy("inv:unidad_medida_list")
    
    def form_valid(self, form):
        form.instance.usuario_Crea = self.request.user
        return super().form_valid(form)


class UnidadMedidaEdit(SinPrivilegios, generic.UpdateView):
    permission_required = "inv.change_unidadmedida"
    model = UnidadMedida
    template_name = "inv/unidad_medida_form.html"
    context_object_name = "obj"
    form_class = MarcaForm
    success_url = reverse_lazy("inv:unidad_medida_list")
    
    def form_valid(self, form):
        form.instance.usuario_Modifica = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_unidadmedida', login_url='base:sin_privilegios')
def UnidadMedidaInactivar(request, id):
    unidadmedida = UnidadMedida.objects.filter(pk= id).first()
    contexto = {}
    template_name = "inv/marca_del.html"

    if not unidadmedida:
        return redirect("inv:unidad_medida_list")
    
    if request.method=='GET':
        contexto ={'obj': unidadmedida}

    if request.method=='POST':
        unidadmedida.estado = False
        unidadmedida.save()
        return redirect("inv:unidad_medida_list")

    return render(request, template_name, contexto)


#PRODUCTO
class ProductoView(SinPrivilegios, generic.ListView):
    permission_required = "inv.view_producto"
    model = Producto
    template_name = "inv/producto_list.html"
    context_object_name = "obj"
    
class ProductoNew(SinPrivilegios, generic.CreateView):
    permission_required = "inv.add_unidadmedida"
    model = Producto
    template_name = "inv/producto_form.html"
    context_object_name = "obj"
    form_class = ProductoForm
    success_url = reverse_lazy("inv:producto_list")
    
    def form_valid(self, form):
        form.instance.usuario_Crea = self.request.user
        return super().form_valid(form)


class ProductoEdit(SinPrivilegios, generic.UpdateView):
    permission_required = "inv.change_unidadmedida"
    model = Producto
    template_name = "inv/producto_form.html"
    context_object_name = "obj"
    form_class = ProductoForm
    success_url = reverse_lazy("inv:producto_list")
    
    def form_valid(self, form):
        form.instance.usuario_Modifica = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_producto', login_url='base:sin_privilegios')
def ProductoInactivar(request, id):
    producto = Producto.objects.filter(pk= id).first()
    contexto = {}
    template_name = "inv/marca_del.html"

    if not producto:
        return redirect("inv:producto_list")
    
    if request.method=='GET':
        contexto ={'obj': producto}

    if request.method=='POST':
        producto.estado = False
        producto.save()
        return redirect("inv:producto_list")

    return render(request, template_name, contexto)

app/inv/templates/inv/marca_list.html
{% extends 'base/base.html' %}

{% block page_content %} 

    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Marcas</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Acciones</div>
                    <a class="dropdown-item" href="{% url 'inv:marca_new' %}"><i class="far fa-calendar-plus"></i>Nuevo</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
                <div class="alert alert-info">No hay marcas</div>
            {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Id</th>
                        <th>Descripcion</th>
                        <th>Estado</th>
                        <th>Fec. Creado</th>
                        <th>Fec. Modificado</th>
                        <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                        {% for item in obj %}
                            <tr>
                                <td>{{ item.id }}</td>
                                <td>{{ item.descripcion }}</td>
                                <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                                <td>{{ item.fecha_Creacion|date:"d/m/Y H:i:s" }}</td>
                                <td>{{ item.fecha_Modificado|date:"d/m/Y H:i:s" }}</td>
                                <td>
                                    <a href="{% url 'inv:marca_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'inv:marca_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}            
        </div>
    </div>

{% endblock %}
{% block js_page %} 
<script>
    //Call the dataTable
    $(document).ready(function(){
        $('.table').DataTable();
    });
</script>
{% endblock %}

app/inv/templates/inv/producto_list.html
{% extends 'base/base.html' %}

{% block page_content %} 

    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Productos</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Acciones</div>
                    <a class="dropdown-item" onclick="return abrir_modal('{% url 'inv:producto_new' %}')" href="#"><i class="far fa-calendar-plus"></i>Nuevo</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
                <div class="alert alert-info">No hay productos</div>
            {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Sub. Cat.</th>
                        <th>Codigo</th>
                        <th>Barra</th>
                        <th>Descripcion</th>
                        <th>Existencia</th>
                        <th>Marca</th>                        
                        <th>U.M.</th>
                        <th>Estado</th>
                        <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                        {% for item in obj %}
                            <tr>
                                <td>{{ item.subcategoria }}</td>
                                <td>{{ item.codigo }}</td>
                                <td>{{ item.codigo_barra }}</td>
                                <td>{{ item.descripcion }}</td>
                                <td>{{ item.existencia }}</td>
                                <td>{{ item.marca }}</td>
                                <td>{{ item.unidadmedida }}</td>
                                <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                                <td>
                                    <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'inv:producto_edit' item.id %}')">                                    
                                        <i class="far fa-edit"></i>
                                    </button>                                                                        
                                    <a href="{% url 'inv:producto_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}            
        </div>
    </div>

{% endblock %}
{% block js_page %} 
<script>
    //Call the dataTable
    $(document).ready(function(){
        $('.table').DataTable();
    });
</script>
{% endblock %}

app/inv/templates/inv/subcategoria_list.html
{% extends 'base/base.html' %}

{% block page_content %} 

    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Sub Categorias</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Acciones</div>
                    <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}"><i class="far fa-calendar-plus"></i>Nuevo</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
                <div class="alert alert-info">No hay Sub Categoria</div>
            {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Categoria</th>
                        <th>Id</th>
                        <th>Descripcion</th>
                        <th>Estado</th>
                        <th>Fec. Creado</th>
                        <th>Fec. Modificado</th>
                        <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                        {% for item in obj %}
                            <tr>
                                <td>{{ item.categoria }}</td>
                                <td>{{ item.id }}</td>
                                <td>{{ item.descripcion }}</td>
                                <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                                <td>{{ item.fecha_Creacion|date:"d/m/Y H:i:s" }}</td>
                                <td>{{ item.fecha_Modificado|date:"d/m/Y H:i:s" }}</td>
                                <td>
                                    <a href="{% url 'inv:subcategoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'inv:subcategoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}            
        </div>
    </div>

{% endblock %}
{% block js_page %} 
<script>
    //Call the dataTable
    $(document).ready(function(){
        $('.table').DataTable();
    });
</script>
{% endblock %}

app/inv/templates/inv/unidad_medida_list.html
{% extends 'base/base.html' %}

{% block page_content %} 

    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Unidades de Medida</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Acciones</div>
                    <a class="dropdown-item" href="{% url 'inv:unidad_medida_new' %}"><i class="far fa-calendar-plus"></i>Nuevo</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
                <div class="alert alert-info">No hay unidades de medida</div>
            {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Id</th>
                        <th>Descripcion</th>
                        <th>Estado</th>
                        <th>Fec. Creado</th>
                        <th>Fec. Modificado</th>
                        <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                        {% for item in obj %}
                            <tr>
                                <td>{{ item.id }}</td>
                                <td>{{ item.descripcion }}</td>
                                <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                                <td>{{ item.fecha_Creacion|date:"d/m/Y H:i:s" }}</td>
                                <td>{{ item.fecha_Modificado|date:"d/m/Y H:i:s" }}</td>
                                <td>
                                    <a href="{% url 'inv:unidad_medida_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'inv:unidad_medida_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}            
        </div>
    </div>

{% endblock %}
{% block js_page %} 
<script>
    //Call the dataTable
    $(document).ready(function(){
        $('.table').DataTable();
    });
</script>
{% endblock %}